# Generated by Django 4.2.6 on 2023-10-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valantyorlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='media/')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
