# Generated by Django 4.2.6 on 2023-10-10 17:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(help_text='Yangilik sarlavhasi', max_length=200)),
                ('slug', models.SlugField(help_text="Slug buni yozishingiz shart emas o'zi yozib beradi !", max_length=200)),
                ('rasm', models.ImageField(help_text="Yangilik uchun kamida 1 ta rasm qo'yish shart", upload_to='media/')),
                ('nashr_vaqti', models.DateTimeField(auto_now_add=True)),
                ('matn', ckeditor.fields.RichTextField(help_text='Yangilik matni')),
                ('kategoriya', models.ForeignKey(help_text="Ushbu ma'lumot qaysi viloyatga tegishliligi", on_delete=django.db.models.deletion.CASCADE, to='news.kategoriya')),
            ],
            options={
                'verbose_name': 'Yangiliklar',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
